use tabledb;

DROP TABLE IF EXISTS buyTBL;
DROP TABLE IF EXISTS userTBL;

CREATE TABLE userTBL
(
    userID    CHAR(8)     NOT NULL PRIMARY KEY,
    name      VARCHAR(10) NOT NULL,
    birthyear INT         NOT NULL
);

CREATE TABLE buyTBL
(
    num      INT     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userID   CHAR(8) NOT NULL,
    prodName CHAR(6) NOT NULL
);

ALTER TABLE buyTBL
ADD CONSTRAINT fk_userID
FOREIGN KEY (userID) REFERENCES userTBL(userID);

